services:
  db:
    image: mysql:8.0.35
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;' --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - ~/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3308:3306'
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/study_hub
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
